export const FETCH_ALL_CATEGORY_PENDING = "FETCH_ALL_CATEGORY_PENDING";
export const FETCH_ALL_CATEGORY_SUCCESS = "FETCH_ALL_CATEGORY_SUCCESS";
export const FETCH_ALL_CATEGORY_FAILED = "FETCH_ALL_CATEGORY_FAILED";

export const FETCH_ONE_CATEGORY_PENDING = "FETCH_ONE_CATEGORY_PENDING";
export const FETCH_ONE_CATEGORY_SUCCESS = "FETCH_ONE_CATEGORY_SUCCESS";
export const FETCH_ONE_CATEGORY_FAILED = "FETCH_ONE_CATEGORY_FAILED";

export const ADD_CATEGORY_PENDING = "ADD_CATEGORY_PENDING";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";

export const REMOVE_CATEGORY_PENDING = "REMOVE_CATEGORY_PENDING";
export const REMOVE_CATEGORY_SUCCESS = "REMOVE_CATEGORY_SUCCESS";
export const REMOVE_CATEGORY_FAILED = "REMOVE_CATEGORY_FAILED";

export const UPDATE_CATEGORY_PENDING = "UPDATE_CATEGORY_PENDING";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILED = "UPDATE_CATEGORY_FAILED";

export const BASE_URL = "http://localhost:8000/category";
